name: Optional CI

on: [push]

jobs:
  build: 
    runs-on: ubuntu-18.04
    container: ${{matrix.container}}
    strategy:
      matrix:
        container: [conanio/gcc5, conanio/gcc6, conanio/clang7]
          
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ls && mkdir build && cd build && cmake .. && cmake --build .
