name: Optional CI

on: [push]

jobs:
  build: 
    strategy:
      matrix:
        container: [conanio/gcc49, conanio/gcc5]

    runs-on: ubuntu-18.04 
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: mkdir build && cd build && cmake .. && cmake --build .