name: Optional CI

on: [push]

jobs:
  build: 
    runs-on: ${{ matrix.os }}
    container: conanio/${{ matrix.compiler[0] }}
    strategy:
      matrix:
        compiler: [[gcc49,g++-4.9], [gcc5, g++-5.0], [clang50, clang++-5.0]]
        os: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: sudo mkdir build && cd build && sudo cmake -DCMAKE_CXX_COMPILER=${{matrix.compiler[1]}} ..
    - name: build
      run: cmake --build .
