name: Optional CI

on: [push]

jobs:
  build: 
    runs-on: ${{ matrix.os }}
    container: conanio/${{compiler}}
    strategy:
      matrix:
        compiler: [gcc49, gcc50, gcc51, gcc52, clang5, clang6, clang7]
        os: [ubuntu-18.04]
        includes:
          - os: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=${{matrix.compiler}} .. 
    - name: build
      run: cmake --build .
