name: Optional CI Linux 

on: [push]

jobs:
  build: 
    runs-on: ubuntu-18.04
    container: conanio/${{matrix.container}}
    strategy:
      matrix:
        container: [gcc48, gcc49, gcc52, gcc53, gcc54, gcc63, gcc64, gcc7, gcc72, gcc8, gcc9, clang38, clang39, clang40, clang50, clang60, clang7, clang8]
          
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: sudo mkdir build && cd build && sudo cmake .. && sudo cmake --build .
    - name: test
      run: ./build/tests
